apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
  labels:
    name: spring-app-deploy
    app: demo-spring-app
spec:
  template:
    metadata:
      name: spring-app-pod
      labels:
        name: spring-app-pod
        app: demo-spring-app
    spec:
      containers:
        - name: spring-app
          image: nareshpenchikala/kube-spring:latest
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      name: spring-app-pod
      app: demo-spring-app
  replicas: 2
  
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    name: spring-service
    app: demo-spring-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
  selector:
    name: spring-app-pod
    app: demo-spring-app

